exports.athletes = [
    {
    firstname:"Russell",
    lastname:"Westbrook",
    sport:"Basketball",
    league:"NBA",
    team:"Houston Rockets",
    birthday:"11/12/88",
    position:"Point guard",
    picture: "russel-westbrook.jpg"
    },
    {
    firstname:"Kevin",
    lastname:"Durant",
    sport:"Basketball",
    league:"NBA",
    team:"Brooklyn Nets",
    birthday:"09/29/88",
    position:"Forward",
    picture:"kevin-durant.jpg",
    },
    {
    firstname:"Skylar",
    lastname:"Diggins-Smith",
    sport:"Basketball",
    league:"WNBA",
    team:"Dallas Wings",
    birthday:"08/02/90",
    position:"Point guard",
    picture:"skylar-diggins.jpg",
    },
    {
    firstname:"Tom",
    lastname:"Brady",
    sport:"Football",
    league:"NFL",
    team:"New England Patriots",
    birthday:"08/03/77",
    position:"Quaterback",
    picture:"tom-brady.jpg",
    },
    {
    firstname:"A'ja",
    lastname:"Wilson",
    sport:"Basketball",
    league:"WNBA",
    team:"Las Vegas Aces",
    birthday:"08/08/96",
    position:"Forward",
    picture:"a'ja-wilson.jpg",
    },
    {
    firstname:"Kobe",
    lastname:"Bryant",
    sport:"Basketball",
    leauge:"NBA",
    team:"LA Lakers",
    birthday:"08/23/78",
    position:"Shooting Guard",
    picture:"kobe-bryant.jpg",
    },
]